# Generated by Django 3.2.15 on 2022-09-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=225)),
                ('model', models.CharField(max_length=225)),
                ('network_technology', models.CharField(max_length=225)),
                ('t2G_bands', models.CharField(max_length=225)),
                ('t3G_bands', models.CharField(max_length=225)),
                ('t4G_bands', models.CharField(max_length=225)),
                ('network_speed', models.CharField(max_length=225)),
                ('GPRS', models.CharField(max_length=225)),
                ('EDGE', models.CharField(max_length=225)),
                ('announced', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('dimentions', models.CharField(max_length=225)),
                ('weight_g', models.CharField(max_length=225)),
                ('weight_oz', models.CharField(max_length=225)),
                ('SIM', models.CharField(max_length=225)),
                ('display_type', models.CharField(max_length=225)),
                ('display_resolution', models.CharField(max_length=225)),
                ('display_size', models.CharField(max_length=225)),
                ('OS', models.CharField(max_length=225)),
                ('CPU', models.CharField(max_length=225)),
                ('Chipset', models.CharField(max_length=225)),
                ('GPU', models.CharField(max_length=225)),
                ('memory_card', models.CharField(max_length=225)),
                ('internal_memory', models.CharField(max_length=225)),
                ('RAM', models.CharField(max_length=225)),
                ('primary_camera', models.CharField(max_length=225)),
                ('secondary_camera', models.CharField(max_length=225)),
                ('loud_speaker', models.CharField(max_length=225)),
                ('audio_jack', models.CharField(max_length=225)),
                ('WLAN', models.CharField(max_length=225)),
                ('bluetooth', models.CharField(max_length=225)),
                ('GPS', models.CharField(max_length=225)),
                ('NFC', models.CharField(max_length=225)),
                ('radio', models.CharField(max_length=225)),
                ('USB', models.CharField(max_length=225)),
                ('sensors', models.CharField(max_length=225)),
                ('battery', models.CharField(max_length=225)),
                ('colors', models.CharField(max_length=225)),
                ('approx_price', models.PositiveIntegerField()),
                ('img_url', models.CharField(max_length=225)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
    ]
