# Generated by Django 3.2.15 on 2022-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20220909_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approx_price',
            field=models.CharField(max_length=500),
        ),
    ]
