# Generated by Django 3.2.15 on 2022-09-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_product_approx_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approx_price',
            field=models.IntegerField(default=None),
        ),
    ]
